NHSDigital/identity-service-api

azure-pipelines.yml, proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml, terraform/main.tf, terraform/variables.tf
* :robot: Deploys pull requests in their own namespace
=> APM-501 Add namespaced pull request deploys

terraform/main.tf
* Align to new api-platform-service-module changes
=> Apm 634 fix api products

.github/workflows/continuous-integration.yml, azure-pipelines.yml
=> APM-647 Add Node install step

CHANGELOG.md, azure-pipelines.yml
* Replace invalid characters in branch name
=> Apm 647 test with / in name

CHANGELOG.md, README.md, package-lock.json, specification/components/responses/InvalidRequest.yaml, specification/components/responses/Unauthorized.yaml, specification/components/schemas/ErrorResponse.yaml, specification/identity-service.yaml
* Update the spec to define the /authorize and /token endpoints
=> APM-770 Identity Spec

CHANGELOG.md, proxies/live/apiproxy/policies/AssignMessage.AuthCodeRedirect.xml, proxies/live/apiproxy/policies/OAuthV2.GenerateAuthCode.xml, proxies/live/apiproxy/proxies/default.xml
* Remove the scope query param from the callback redirection
=> Remove the scope query param from the callback redirection

CHANGELOG.md, proxies/live/apiproxy/policies/AssignMessage.GenerateRefreshTokenResponse.xml, proxies/live/apiproxy/policies/AssignMessage.GenerateTokenResponse.xml, specification/identity-service.yaml
* Remove token id from responses
=> APM-421 Remove id_token from response

CHANGELOG.md, proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetVariables.xml, proxies/live/apiproxy/targets/identity-server.xml
=> Templating necessary to support multiple identity services per env

proxies/live/apiproxy/policies/ServiceCallout.GetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.PostToken.xml
* Found we need additional templating hooks in the service callouts (bugfix)
=> also template the service callouts

azure/azure-pr-pipeline.yml
* Stop build trigger for pr pipeline
=> APM-882 Stop build trigger for pr pipeline

azure/templates/download-build-artifact.yml
* Fix where the release looks for the artifact when building from tags
=> APM-882 Fix release artifact referencing

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/templates/download-build-artifact.yml
* Change release pipeline trigger to kick off after build pipeline has completed
=> Apm 882 Change release pipeline trigger

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml, proxies/live/apiproxy/proxies/default.xml
=> apm-357: add splunk logging post client flow

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/components/notify-github-finished.yml, azure/components/notify-github-pending.yml
* :robot: Set status checks manually from the PR deploy pipeline
* :warning: Remove caching in build pipeline since it appears to be broken
=> APM-1162 Fix pull request status check

.gitignore, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/components/get-aws-secrets-and-ssm-params.yml, azure/templates/identity-service-templating.yml
=> Pull build secrets from AWS

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/components/get-access-token.yml, azure/components/get-aws-secrets-and-ssm-params.yml, azure/components/notify-github-pending.yml, azure/templates/deploy-namespaced-service.yml, azure/templates/deploy-service.yml, azure/templates/deploy-specs.yml
Hotfix the variables used to build AWS param names
=> APM 1012 hotfix AWS env names

azure/azure-release-pipeline.yml, azure/components/get-access-token.yml, azure/components/get-aws-secrets-and-ssm-params.yml, azure/components/notify-github-pending.yml, azure/templates/deploy-namespaced-service.yml, azure/templates/deploy-service.yml, azure/templates/deploy-specs.yml
=> Delete variables that are no longer required

azure/azure-release-pipeline.yml, azure/templates/deploy-service.yml
=> Bs apm 1012 build secrets from aws

azure/templates/deploy-namespaced-service.yml
* Add namespace to product display name as previous all products named the same.
=> APM-1104 Add namespace to display name

azure/azure-release-pipeline.yml, azure/templates/deploy-namespaced-service.yml, azure/templates/identity-service-templating.yml
* Set KVM variables for int-no-smartcard env
=> APM-1279 Get int-no-smartcard variables from correct location

proxies/live/apiproxy/proxies/default.xml
* Disable the rate limiting as implemented
See https://nhsd-jira.digital.nhs.uk/browse/APM-1302
=> temporarily disable rate limiting

azure/azure-release-pipeline.yml
=> APM-1213 Common pipelines

CHANGELOG.md, api_tests/README.md, api_tests/config_files/environments.py, api_tests/scripts/authenticator.py, api_tests/scripts/generic_request.py, api_tests/scripts/response_bank.py, api_tests/steps/check_oauth_endpoints.py, api_tests/tests/conftest.py, api_tests/tests/oauth/token_refresh/test_error_responses.py, api_tests/tests/oauth/token_refresh/test_happy_path.py, azure/azure-pr-pipeline.yml
=> APM-1327 Add 'simulated OAuth' as an authentication option for the oauth tests

azure/azure-release-pipeline.yml
=> APM-1162 Hotfix to add short_service_name in release pipeline

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
=> APM-1356 Disable ping

proxies/live/apiproxy/policies/RaiseFault.CheckResponseType.xml, proxies/live/apiproxy/proxies/default.xml
* Validate response type = 'code'
Reference RFC: https://tools.ietf.org/html/rfc6749#section-4.1.2.1
=> APM-990 Validate response type

api_tests/config_files/config.py, api_tests/scripts/generic_request.py, api_tests/tests/oauth/test_oauth_endpoints.py, api_tests/tests/oauth/test_oauth_tokens.py, api_tests/tests/pytest.ini
Updated authorise endpoint error condition test
=> Apm 990 validate response type on authorize endpoint

api_tests/config_files/config.py
=> APM-990 toggle flag

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/live/apiproxy/policies/AssignMessage.GenerateState.xml, proxies/live/apiproxy/policies/Python.GenerateState.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/py/generate-state.py
Use a python callout to get cryptographically secure random numbers of
sufficient length that are nicely formatted for use as tokens in query
parameters.
----
=> APM-991 Use cryptographically secure state2.

api_tests/scripts/generic_request.py, azure/azure-release-pipeline.yml
=> APM-991 Fix test logic and release pipeline

proxies/live/apiproxy/proxies/default.xml
=> fix attempt

api_tests/tests/oauth/test_oauth_tokens.py
=> Apm 1335 - error response from expired refresh token is incorrect

proxies/live/apiproxy/policies/AssignMessage.SetClientCredentials.xml, proxies/live/apiproxy/policies/LookupCache.JTIClaim.xml, proxies/live/apiproxy/policies/PopulateCache.JTIClaim.xml, proxies/live/apiproxy/policies/VerifyAPIKey.FromJWT.xml, proxies/live/apiproxy/proxies/default.xml
For testing error messages and changing naming conventions which were broken
=> APM-1529 changes subject to sub for any claim that uses it

proxies/live/apiproxy/policies/OAuthV2.ClientCredentialsGenerateAccessToken.xml, proxies/live/apiproxy/proxies/default.xml
=> APM-1541 Allow reduction of access token expiry time

proxies/live/apiproxy/policies/JavaScript.CalculateNowPlusSixMins.xml, proxies/live/apiproxy/policies/RaiseFault.ExpClaimTooLong.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/calculate-now-plus-six-mins.js
=> Check that the exp of the JWT isn't more than 5 minutes in the future

api_tests/config_files/config.py, api_tests/tests/oauth/test_oauth_endpoints.py, api_tests/tests/pytest.ini, proxies/live/apiproxy/proxies/default.xml
The client_id sent in the queryparam to the GET /callback handler should be correct; processing should halt if not.
=> Validate incoming client_id

api_tests/config_files/config.py, api_tests/config_files/environments.py, api_tests/scripts/authenticator.py, api_tests/scripts/generic_request.py, api_tests/tests/oauth/test_oauth_endpoints.py, api_tests/tests/pytest.ini, azure/azure-pr-pipeline.yml, azure/templates/run-integration-tests.yml, poetry.lock
* Update tests to run on PR
* Skipping cache scoping tests to unblock others
=> Apm 992 cache scoping

api_tests/config_files/config.py, api_tests/tests/oauth/test_oauth_endpoints.py, api_tests/tests/pytest.ini, proxies/live/apiproxy/policies/AssignMessage.CacheKeyError.xml, proxies/live/apiproxy/policies/InvalidateCache.OriginalClientInfo.xml, proxies/live/apiproxy/proxies/default.xml
=> APM-993 Remove Client info state from cache after use

.github/workflows/continuous-integration.yml, .github/workflows/pr-lint.yaml
=> APM-1162 Allow ::set-env

.github/workflows/pr-lint.yaml
=> APM-1623 Add ACTIONS_ALLOW_UNSECURE_COMMANDS to set-env action

api_tests/tests/oauth/test_oauth_tokens.py
=> APM-1618 Add test for POST w/ query params

azure/azure-pr-pipeline.yml, proxies/live/apiproxy/policies/DecodeJWT.FromGeneratedIdTokenSimulatedAuth.xml, proxies/live/apiproxy/policies/GenerateJWT.SimulatedAuth.xml, proxies/live/apiproxy/policies/OAuthV2.GenerateAccessToken.xml, proxies/live/apiproxy/policies/OAuthV2.GenerateAccessTokenSimulatedAuth.xml, proxies/live/apiproxy/proxies/default.xml
=> Add ACR and AMR attributes to access token

azure/azure-pr-pipeline.yml
* Add internal-dev-int stage to PR for integration testing
=> APM-1683 Add internal-dev int stage

azure/azure-release-pipeline.yml
=> APM-1631 Add path to unsubscribed client id and secret

api_tests/config_files/config.py, api_tests/tests/oauth/test_oauth_endpoints.py, proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml, proxies/live/apiproxy/proxies/default.xml
=> apm-1674 - added test for _ping endpoint

proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml, proxies/live/apiproxy/proxies/default.xml
=> APM-1674 Add flow AddPayloadToPing

api_tests/scripts/generic_request.py, api_tests/scripts/response_bank.py, proxies/live/apiproxy/policies/AssignMessage.GenerateUserinfoResponseSimulatedAuth.xml, proxies/live/apiproxy/policies/AssignMessage.SetAuthorizationRedirect.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetVariables.xml
- Assign the userinfo_path variable from the KVM
- Add the nationalrbacaccess scope so we get user roles back from the IdP
- Update the simulated_auth response to look like the real thing
=> AEA-756: Corrections to the userinfo endpoint following testing in int

azure/azure-release-pipeline.yml
Enables monitoring on identity-service releases
=> APM-1674 Enable monitoring

proxies/live/apiproxy/proxies/default.xml
=> APM-1475 Readd mis-removed policy

.gitignore, api_tests/performance/README.md, api_tests/performance/locustfile.py, api_tests/performance/poetry.lock, api_tests/performance/pyproject.toml, proxies/live/apiproxy/proxies/default.xml
* Add rate limit policies for app restricted
=> APM-1704 apply ratelimit app restricted

api_tests/tests/oauth/test_jwt_unattended_access.py, proxies/live/apiproxy/policies/AssignMessage.PublicKeyMisconfigured.xml
Change error message for misconfigured public key from 500 to 403
=> APM-1814 Change 500 to 403 for misconfigured publickey

proxies/live/apiproxy/policies/AssignMessage.SimulatedAuthPage.xml
Change the link and wording for user-restricted info link on simulated auth app
=> APM-1827 Change link and wording for user-restricted info link

api_tests/scripts/response_bank.py
=> APM-1827 Fix tests for sim auth page

azure/azure-release-pipeline.yml
=> amb-514 hotfix master branch

api_tests/config_files/environments.py, api_tests/tests/oauth/test_oauth_endpoints.py, proxies/live/apiproxy/policies/AssignMessage.TokenExchangeGenerateTokenResponse.xml
=> AMB-548 add additional property to payload

api_tests/requirements.txt, api_tests/scripts/generic_request.py, api_tests/tests/conftest.py, api_tests/tests/oauth/test_jwt_unattended_access.py, azure/templates/run-integration-tests.yml
=> Apm 1876 - fix pipeline tests

api_tests/tests/oauth/test_jwt_unattended_access.py
=> APM-1876 - Temp fix for pipeline tests

manifest_template.yml
=> AMB-574 Added missing dev environement to manifest file

proxies/live/apiproxy/policies/GenerateJWT.SimulatedAuth.xml
Add an extra attribute to simulated id_token within simulated access token.
=> AMB-558 Add selected_rolid atribute to simulated id_token

api_tests/scripts/response_bank.py, proxies/live/apiproxy/policies/AssignMessage.GenerateUserinfoResponseSimulatedAuth.xml
Add a role to simulated auth user info response payload.
=> AMB-563 Add role to simulated auth user info response

azure/azure-release-pipeline.yml
=> AMB-582 move testing secrets into internal-dev stage

proxies/live/apiproxy/policies/Javascript.UnpackVars.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetIdentityServiceConfig.xml, proxies/live/apiproxy/resources/jsc/UnpackVars.js
=> AMB 608 - extract identity-service config from kvm

proxies/live/apiproxy/policies/KeyValueMapOperations.GetIdentityServiceConfig.xml, proxies/live/apiproxy/policies/ServiceCallout.GetJWKS.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/UnpackVars.js
=> Amb 608 - unpack kvm vars

proxies/live/apiproxy/policies/AssignMessage.SimulatedAuthPage.xml, proxies/live/apiproxy/policies/GenerateJWT.SimulatedAuth.xml, proxies/live/apiproxy/policies/LookupCache.SimulatedAuthAuthMethod.xml, proxies/live/apiproxy/policies/PopulateCache.SimulatedAuthAuthMethod.xml, proxies/live/apiproxy/proxies/default.xml
=> Add non-smartcard auth methods to simulated auth

proxies/live/apiproxy/policies/AssignMessage.RatelimitExceeded.xml, proxies/live/apiproxy/proxies/default.xml
* Return appropriate rate limit error message
=> APM-2036 Add ratelimit error message

proxies/live/apiproxy/policies/LookupCache.SimulatedAuthAuthMethod.xml, proxies/live/apiproxy/proxies/default.xml
=> AEA-1345: Fix selection of auth method in simulated auth.

proxies/live/apiproxy/policies/OAuthV2.TokenExchangeGenerateAccessTokenFilteredScopes.xml
=> AMB-573 add id_token-subject to access token

manifest_template.yml
=> apm-2134: raise rate limit in REF to 5000/s

api_tests/tests/oauth/test_jwt_unattended_access.py, proxies/live/apiproxy/policies/AssignMessage.RenameQuotaVarsFromVerifyAPIKeyPolicyFromJWT.xml, proxies/live/apiproxy/proxies/default.xml
-------
Fix for https://nhsd-jira.digital.nhs.uk/browse/APM-2104 
=> APM-2104 Rename Quota vars before applying SpikeArrest in JWT flow

manifest_template.yml
Register the `internal-qa-int` proxy to the `internal-qa` product as part of the pipeline
=> Register internal-qa-int proxy to internal-qa product

proxies/live/apiproxy/proxies/default.xml
AMB-725 move spike arrest and quota policy before service callouts.
=> AMB-725 move spike arrest and quota policy before service callout

e2e/Makefile, poetry.lock, pyproject.toml
Install pytest-reruns to rerun failed tests...
=> AMB-759 Install and configure pytest-reruns

proxies/live/apiproxy/policies/GenerateJWT.NHSLoginClientAssertion.xml, proxies/live/apiproxy/proxies/default.xml
=> AMB-722 fix generate JWT policy + condition on JWKS callout

azure/azure-release-pipeline.yml
=> AMB-468 disable status monitoring

e2e/requirements.txt, poetry.lock, pyproject.toml
=> AMB-779 bump test-utils version

e2e/README.md, e2e/tests/oauth/test_jwt_unattended_access.py
=> AMB-775 started pull request

e2e/README.md, e2e/tests/conftest.py, e2e/tests/oauth/test_product_scopes.py
=> AMB-778 Created pull request

e2e/Makefile, e2e/tests/conftest.py, e2e/tests/oauth/test_product_scopes.py
Creating scoped fixtures to improve testing and reduce deployment time
=> AMB-684 create class scoped fixture for testing apigee scopes

azure/azure-release-pipeline.yml
Include the proper ratelimiting values elsewhere in the code
=> APM-2191 Include RATELIMITING in other jina_templates

azure/azure-release-pipeline.yml
=> AMB-000 fix int no smartcard

proxies/live/apiproxy/policies/PopulateCache.SessionId.xml
https://nhsd-jira.digital.nhs.uk/browse/APM-2522
=> APM-2522 Change session-id cache expire to refresh_token expiry time

proxies/live/apiproxy/policies/PopulateCache.SessionId.xml
https://nhsd-jira.digital.nhs.uk/browse/APM-2522
=> APM-2522 Cache refresh_token in cache rather than access_token

proxies/live/apiproxy/resources/jsc/AddSidToResponse.js
=> APM-2521 Set default string value for sid in token

azure/azure-release-pipeline.yml
=> APM-2521 Added new environments for cis2-mock

e2e/tests/oauth/test_backchannel_logout.py, proxies/live/apiproxy/policies/ServiceCallout.ClientCredentialsGrantGetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.GetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.GetNHSLoginJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.PostTokenCis2.xml, proxies/live/apiproxy/policies/ServiceCallout.PostTokenNHSLogin.xml, proxies/live/apiproxy/policies/ServiceCallout.cis2GetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.nhsLoginGetJWKS.xml
=> Added user agent header to service callout

proxies/live/apiproxy/policies/ServiceCallout.ClientCredentialsGrantGetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.GetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.GetNHSLoginJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.PostTokenCis2.xml, proxies/live/apiproxy/policies/ServiceCallout.PostTokenNHSLogin.xml, proxies/live/apiproxy/policies/ServiceCallout.cis2GetJWKS.xml, proxies/live/apiproxy/policies/ServiceCallout.nhsLoginGetJWKS.xml
=> APM-TRIAGE fixed user-agent header issue

e2e/tests/oauth/test_oauth_endpoints.py, proxies/live/apiproxy/policies/RaiseFault.UserInfoWrongAuth.xml, proxies/live/apiproxy/proxies/default.xml
https://nhsd-jira.digital.nhs.uk/browse/APM-2751
=> APM-2751 Update error for wrong auth type on userinfo

proxies/live/apiproxy/proxies/default.xml
=> APM-657 Make nhs-cis2 string for BCL correct comparison on caching

azure/azure-release-pipeline.yml
Keycloak needs it's own client secret for internal-qa mock auth
=> APM-2913 Use keycloak client secret

azure/azure-release-pipeline.yml
=> APM-2016 Add client secret kvm for ref

azure/azure-release-pipeline.yml
=> APM-3226 wire internal-qa-smartcard to nhs-login aos environment

e2e/tests/oauth/test_oauth_tokens.py, proxies/live/apiproxy/policies/AssignMessage.AccessTokenExpiryOverride.xml, proxies/live/apiproxy/policies/AssignMessage.AccessTokenExpiryOverrideAuthType.xml, proxies/live/apiproxy/policies/AssignMessage.SetAccessTokenExpiry.xml, proxies/live/apiproxy/policies/JavaScript.CalculateAccessTokenOverride.xml, proxies/live/apiproxy/policies/OAuthV2.ClientCredentialsGenerateAccessToken.xml, proxies/live/apiproxy/policies/OAuthV2.ClientCredentialsGenerateAccessTokenFilteredScopes.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/calculate-access-token-override.js
Combine AccessTokenExpiryOverride, AccessTokenExpiryOverrideAuthType policies  by setting apigee.access_token_expiry_ms as the value of identity-service-config.cis2.access_token_expiry_ms in client credentials flow.
=> Added new assign message

README.md, e2e/README.md
=> AMB-1176: Update readmes

azure/azure-release-pipeline.yml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
=> AMB-1270 update int-mock to use testing private key

azure/azure-release-pipeline.yml, e2e/tests/conftest.py
=> APM-3427 Add param on mock test runs

azure/azure-release-pipeline.yml
=> AMB-1274 add a sandbox-mock release for Hello World tutorial use

e2e/tests/oauth/test_client_credentials.py
=> APM-2975 fix tests

azure/azure-release-pipeline.yml
=> AMB-1281 add keycloak client secret for Sandbox release

e2e/scripts/config.py, e2e/scripts/response_bank.py, e2e/tests/oauth/test_authorization_code.py, e2e/tests/oauth/test_client_credentials.py, manifest_template.yml, poetry.lock
https://nhsd-jira.digital.nhs.uk/browse/APM-3431
=> APM-3431 Refactor Authorization Code tests

azure/azure-release-pipeline.yml, e2e/tests/oauth/test_backchannel_logout.py, proxies/live/apiproxy/resources/jsc/check-apigee-access-token-attributes.js
=> AMB-1281 update access token check

poetry.lock, pyproject.toml
=> AMB-1281 update packages

azure/azure-pr-pipeline.yml
=> AMB-000 fix pr pipeline

e2e/tests/oauth/test_token_exchange.py
=> APM-3628 Update JWT Signature Test

proxies/live/apiproxy/resources/jsc/validate-id-token-claims.js
=> APM-1681 Make ide token errors specific

.github/workflows/continuous-integration.yml, e2e/tests/oauth/test_authorization_code.py, e2e/tests/oauth/test_backchannel_logout.py, e2e/tests/oauth/test_client_credentials.py, e2e/tests/oauth/test_token_exchange.py, poetry.lock, pyproject.toml
=> APM-3433 Update tests to work with most recent test-utils 2.0 version

e2e/tests/conftest.py, e2e/tests/logging/test_attach_logging_fields.py, e2e/tests/logging/test_splunk_logging.py, e2e/tests/oauth/test_authorization_code.py, e2e/tests/oauth/test_backchannel_logout.py, e2e/tests/oauth/test_client_credentials.py, e2e/tests/oauth/test_token_exchange.py, e2e/tests/oauth/utils/helpers.py, poetry.lock, proxies/live/apiproxy/policies/AssignMessage.SetPrBranchRedirectUri.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/set-logging-fields.js, proxies/live/apiproxy/resources/jsc/setDefaultAccessAndRefreshTokenTimes.js, pyproject.toml
=> APM-3433 Refactor Logging tests

e2e/tests/logging/test_splunk_logging.py
=> APM-3433 Add markers so tests pass on internal-dev

azure/azure-release-pipeline.yml
=> APM-3740: Point to cis2-dep target server

e2e/tests/oauth/test_authorization_code.py, proxies/live/apiproxy/policies/JavaScript.CalculateRefreshTokenExpiresIn.xml, proxies/live/apiproxy/policies/OAuthV2.GenerateRefreshToken.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/calculate-refresh-token-expires-in.js
* Calculate the true refresh token expiry time, taking into account both the intended lifetime of an individual refresh token, and the lifetime of *all* refresh tokens from the initial authorization
=> APM-3898: Calculate the 'true' refresh token expiry time

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, manifest_template.yml
=> APM-3686 Retire mock auth v1

Makefile, azure/azure-release-pipeline.yml
=> APM-3686 Rename stages to solve depends issues

azure/azure-release-pipeline.yml
=> APM-3686 Change target servers for nhs-login mock

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/project.yml
=> APM-3686 Extract jinja templates

Makefile, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
=> APM-3686 Use seperate config for oauth2

azure/azure-release-pipeline.yml
=> APM-3686 change providers to keycloak for ptl oauth2

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/live/apiproxy/proxies/default.xml
=> APM-3686 Add client secret in to proxy config

azure/azure-release-pipeline.yml
=> APM-3686 Add back in keycloak client secret

proxies/live/apiproxy/policies/OAuthV2.TokenExchangeGenerateAccessToken.xml, proxies/live/apiproxy/policies/OAuthV2.TokenExchangeGenerateAccessTokenFilteredScopes.xml
=> APM-5380: Add identity service token vars

e2e/tests/conftest.py, proxies/live/apiproxy/policies/OAuthV2.TokenExchangeGenerateAccessTokenFilteredScopes.xml
=> APM-5380 try to get the token exchange flow vars from the subject token

proxies/live/apiproxy/policies/OAuthV2.GenerateAccessToken.xml, proxies/live/apiproxy/policies/OAuthV2.TokenExchangeGenerateAccessTokenFilteredScopes.xml
=> APM-5267: Add identity_proofing_level

package-lock.json
=> APM-6126-MinimistDependabotIssue
